"""initial migration

Revision ID: 3c1b735f5206
Revises: 
Create Date: 2025-06-10 18:08:40.060554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1b735f5206'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('internal_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('racenumber', sa.String(), nullable=False),
    sa.Column('departuredate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('departuretime', sa.Time(), nullable=False),
    sa.Column('originport', sa.String(length=3), nullable=False),
    sa.Column('origincityName', sa.String(), nullable=False),
    sa.Column('arrivaldate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrivaltime', sa.Time(), nullable=False),
    sa.Column('destinationport', sa.String(length=3), nullable=False),
    sa.Column('destinationcityName', sa.String(), nullable=False),
    sa.Column('flighttime', sa.String(), nullable=False),
    sa.Column('price_light', sa.Integer(), nullable=False),
    sa.Column('price_optimal', sa.Integer(), nullable=False),
    sa.Column('price_comfort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('internal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
