"""sync database with models

Revision ID: 95732e4ec5a6
Revises: 37e767585b02
Create Date: 2025-06-03 18:01:28.168158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95732e4ec5a6'
down_revision: Union[str, None] = '37e767585b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('racenumber', sa.Integer(), nullable=False),
    sa.Column('departuredate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('departuretime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('originport', sa.String(length=3), nullable=False),
    sa.Column('origincityName', sa.String(), nullable=False),
    sa.Column('arrivaldate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrivaltime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destinationport', sa.String(length=3), nullable=False),
    sa.Column('destinationcityName', sa.String(), nullable=False),
    sa.Column('flighttime', sa.String(), nullable=False),
    sa.Column('price_light', sa.Integer(), nullable=False),
    sa.Column('price_optimal', sa.Integer(), nullable=False),
    sa.Column('price_comfort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
